### ISSUE TITLE
Meteor 1.2+ breaks OAuth Server

### ISSUE THREAD

**Issue by lscordilis** [emmerge/meteor-google-fake#2]
```
(oauth_server.js:398) Error in OAuth Server: Failed to fetch tokeninfo from Google. Cannot read property 'scope' of null
Exception while invoking method 'login' Error: Failed to fetch tokeninfo from Google. Cannot read property 'scope' of null
     at getScopes (meteor://?app/packages/google/google_server.js:92:1)
     at Object.ServiceConfiguration.configurations.findOne.service [ashandleOauthRequest] (meteor://?app/packages/google/google_server.js:14:1)
     at OAuth._requestHandlers.(anonymous function) (meteor://?app/packages/oauth2/oauth2_server.js:8:1)
     at middleware (meteor://?app/packages/oauth/oauth_server.js:173:1)
     at meteor://?app/packages/oauth/oauth_server.js:146:1
```

Removed google-fake and tried accounts-google by itself and it works fine. 

Here are relevant packages and their versions: 

```
emmerge:google-fake      version 0.0.4_2
iron:controller          version 1.0.8
iron:core                version 1.0.8
iron:dynamic-template    version 1.0.8
iron:layout              version 1.0.8
iron:location            version 1.0.9
iron:middleware-stack    version 1.0.9
iron:router              version 1.0.9
iron:url                 version 1.0.9
xolvio:http-interceptor  version 0.4.2
```

**Comment by wheeler** [comment]
Hi @lscordilis, thanks so much for your issue report! I've just published `emmerge:google-fake@0.0.4_3` which should fix this problem. I've also updated the automated test on this project to use `METEOR@1.2.0.2`
